<main>
<section class="formulaire">
<div class="write_new_article">
    <article class="introduction">
	<h2><i class="fa fa-pencil"></i> Rédigez vos meilleurs souvenirs</h2>
    <p>Nous avons tous vécu dans notre vie un moment important, lié à une passion que l'on assouvi depuis plus ou moins de temps. "Mes Plus Belles Passions" vous permet de partager ces moments avec tous nos lecteurs passionnés.</p>
    </article>
    <div class="comments">
	<form class="generic-form" action="add_post.php" method="post">
    
        
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select class="input" id="author" name="author">
                        <?php foreach($aTab as $aValues): ?>
                        <option value="<?= $aValues['Id'];?>"><?= htmlspecialchars($aValues['FirstName'].' '.$aValues['LastName']); ?></option>
                        <?php endforeach ?>
                </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select class="input" id="category" name="category">
                        <?php foreach($aTab2 as $aValues2): ?>
                        <option value="<?= $aValues2['Id'];?>"><?= $aValues2['Name'];?></option>
                        <?php endforeach ?>

                </select>
            </li>
            <li>
                <button id="submit" name="submit" class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    
	</form>
    </div>
	<div style="width: 100%; height: 3em;"></div>
</div>
</section>
<main>