<main>
<section class="formulaire">
<div class="write_new_article">
    <article class="introduction">
    <p>Vous souhaitez prendre contact avec nous. Remplissez le formulaire ci-dessous et nous répondrons à vos questions.</p>
    </article>
    <div class="comments">
	<form class="generic-form" action="contact.php" method="post">
        <ul>
            <li>
                <label for="lastname">Nom :</label>
                <input type="text" id="lastname" name="lastname">
            </li>
             <li>
                <label for="firstname">Prénom :</label>
                <input type="text" id="firstname" name="firstname">
            </li>
             <li>
                <label for="email">Email :</label>
                <input type="text" id="email" name="email">
            </li>
            <li>
                <label class="textarea" for="message">Votre message :</label>
                <textarea id="message" name="message" rows="15"></textarea>
            </li>
            <li>
                <button id="submit" name="submit" class="button button-primary" type="submit">Valider</button>
            </li>
        </ul>
	</form>
    </div>
	<div style="width: 100%; height: 3em;"></div>
</div>
</section>
<main>