<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>blog</title>
	
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script|Playfair+Display"> 
	<link rel="stylesheet" href="css/normalize.css">
	<link rel="stylesheet" href="css/style.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  	<script>tinymce.init({ selector:'textarea' });</script>
</head>
<body>
	<header>
		<h1>Mes plus belles passions</h1>
		<nav>
			<a href="index.php">Accueil</a>
			<a href="add_post.php">Ecrivez vos articles</a>
			<a href="contact.php">Contact</a>
		</nav>
	</header>
	<?php include $template.'.phtml'; ?>
<script>
	$(window).on('load', function() {
			$(".tool-bar").click(function() {
  			$(".hide").fadeToggle();
			});
		});
		
</script>
	<footer>
		<small>
			Copywrite © Loreleï 2018
		</small>
	</footer>
</body>
</html>